create migrations for user and shop tables
xbakhromjon/bug-free-marketplace pull request #2
Opened 2023-11-27 13:02 UTC by asadbek21iman

create migrations for user and shop tables

2023-11-27 13:13 UTC, asadbek21iman commented
i have updated PR so that it would contain product migrations as well

2023-11-27 13:25 UTC, khudayberdiyev25 requested changes

2023-11-27 13:25 UTC, khudayberdiyev25 commented on migrations/000001_users.down.sql
> +DROP TABLE IF EXISTS "users";
add extra line at the end of the file to get rid of this alert

2023-11-27 13:25 UTC, khudayberdiyev25 commented on migrations/000002_shop.up.sql
> +  "user_id" int NOT NULL,
I think better to rename `user_id` to `owner_id`. owner_id sounds more meaningful at shop context.

2023-11-27 13:25 UTC, khudayberdiyev25 commented on docker-compose.yaml
> +      - "5007:5007"
why u changed it ?

2023-11-28 05:48 UTC, asadbek21iman commented on migrations/000001_users.down.sql
> +DROP TABLE IF EXISTS "users";
just empty line?

2023-11-28 06:27 UTC, closed without merging